# Generated by Django 2.1.5 on 2019-01-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=None, max_length=60)),
            ],
            options={
                'db_table': 'Grades',
            },
        ),
    ]
