# Generated by Django 2.1.5 on 2019-01-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0002_grades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Stages',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='step',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='stages',
            old_name='step',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='sections',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allactions.Departments'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stages',
            table='Stages',
        ),
    ]
