# Generated by Django 2.1.5 on 2019-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0003_auto_20190131_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='department',
        ),
        migrations.AddField(
            model_name='questions',
            name='department',
            field=models.ManyToManyField(to='allactions.Departments'),
        ),
    ]
