# Generated by Django 2.1.5 on 2019-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0004_auto_20190201_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hint',
            field=models.TextField(default=None),
        ),
    ]
