# Generated by Django 2.1.5 on 2019-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0005_questions_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
