# Generated by Django 2.1.5 on 2019-02-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0006_auto_20190201_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='stage',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
