# Generated by Django 2.1.5 on 2019-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0008_auto_20190202_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint',
            field=models.TextField(blank=True, default=None, max_length=300),
        ),
    ]
