# Generated by Django 2.1.5 on 2019-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allactions', '0010_auto_20190202_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grades',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stages',
            options={'ordering': ['id']},
        ),
    ]
